### ISSUE TITLE
Undefined enum

### ISSUE THREAD

**Issue by blmarket** [nathankunicki/nuimojs#2] opened 2016-07-06 15:22 UTC
```
nuimojs/src/device.js:180
            case (Nuimo.Direction.LEFT):
                                 ^

TypeError: Cannot read property 'LEFT' of undefined
```

you should export Direction at `nuimo.js`

**Comment by nathankellenicki** [comment] 2016-07-08 11:37
Hi, which version of Node are you using? The export of `nuimo.js` is the Nuimo class, for which there is a static getter for the Direction enum. I'm not able to reproduce this.

**Comment by blmarket** [comment] 2016-07-11 04:30
Reproduction step is not clear enough, sorry about that. it was
1. run examples/interaction.js
2. swipe nuimo to left
3. bang!

Last test was on node version `v6.3.0`.

```
$ node -v
v6.3.0
```

My analysis is here.

As `nuimo.js` and `device.js` are in circular dependency, so `Nuimo.Direction` is undefined when `device.js` is trying to import it. you better remove those circular dependencies.

**Comment by blmarket** [comment] 2016-07-12 01:21
Created PR #4 to fix, PTAL

**Comment by nathankellenicki** [comment] 2016-07-18 20:45
Thank you, tested and works! Merged.

**Closed as completed** 2016-07-18 20:46 UTC

**Comment by blmarket** [comment] 2016-07-19 07:49
:grinning: eager waiting next release!
